### ISSUE TITLE
Engineering Q

### ISSUE THREAD

**Issue by TimSlendebroek** [ProjectTorreyPines/IMAS.jl#32]
Engineering Q == Net electricity

Most of this is in GASC

**Roadmap**
- [x] HCD efficiencies from deposited to plug (absorption, reflection, losses, generation)
- [x] Similar to HCD do not forget about Ohmic heating
- [x] Tritium separation
- [x] Cryo
- [x] Blanket power multiplier
- [x] Efficiency of converting thermal to electric

Questions:
- [x] Where to store information in `dd` ?

Related PRs:
IMASDD: https://github.com/ProjectTorreyPines/IMASDD.jl/pull/2

ToDo:

- [x] Expressions
- [x] Subsystems
- [x] ActorPlantPowerBalance
- [x] init
